### ISSUE TITLE
Confused about "platform" name

### ISSUE THREAD

**Issue by pfeiferbit** [shopwareLabs/shopware-platform-vagrant#10]
Hi,

this isn't really a bug, more like a question for slightly improved documentation. I am quite confused about the difference between this repo, `shopware-platform-vagrant` and the [`shopware-vagrant`](https://github.com/shopwareLabs/shopware-vagrant) repo.

Do both exist because one of them is strictly for developing the core of shopware whereas the other is for Shopware client code (aka. plugins and projects)?

Does one of them just exist for legacy reasons but they mean the same? (I've seen someone calling the other repo the "old one" [here](https://github.com/shopwareLabs/shopware-platform-vagrant/issues/7).)

Mind you, I'm very new to Shopware development as a whole.

Thank you in advane!
Greetings

**Comment by mitelg** [comment]
hey @pfeiferbit 
this repo is for developing with https://github.com/shopware/platform which is the base for Shopware 6.
The other repo is for Shopware 5 https://github.com/shopware/shopware
