### ISSUE TITLE
Payment method not showing on frontend

### ISSUE THREAD

**Issue by thanhnx991** [shopwareLabs/shopware-platform-vagrant#13]
I'm installed plugin https://github.com/shopware/swag-docs-payment-plugin. It show payment on backend but not show on frontend? It only showing default payment

**Comment by mitelg** [comment]
hey @thanhnx991 thanks for reporting. does the error has something to do with the vagrant setup? otherwise I would suggest to open an issue in the example plugin repository :wink:

**Comment by mitelg** [comment]
I just saw, you already did that. will close this one here :blush:

**Comment by thanhnx991** [comment]
Thank for reply
