### ISSUE TITLE
proxy_http_version is not set, default is 1.0 (= no-cache)

### ISSUE THREAD

**Issue by mrdevries** [shopwareLabs/shopware-platform-vagrant#14]
Hi,

When proxy is enabled the following is not set: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

Default will be set to 1.0, which makes Symfony set pragma: no-cache and expires: -1 headers, which in turn makes HttpCache - used in the new Shopware 6 RC - always invalidate. Adding `proxy_http_version 1.1;` below `proxy_pass {{ proxy_upstream }};` in the nginx vhost templates will fix this.

**Comment by flohessling** [comment]
Thank you for your contribution!
I merged the `proxy_http_version` setting with your pull request.
