### ISSUE TITLE
Add checksum for more secure integration

### ISSUE THREAD

**Issue by rikterbeek** [shopwareLabs/shopware-platform-vagrant#16]
Hi,

Would you be able to add a checksum to the vm.box for increasing the security of the integration. By adding this we are allowed to use the vagrant file otherwise we can't.

Regards,
Rik

**Comment by flohessling** [comment]
Hi Rik,

thank you for your contribution.
We are using the `bento/ubuntu-18.04`-box from the chef/bento project (https://github.com/chef/bento) and have not packed our own box. 
You are free to use a box that fits your needs or create your own. The shopware installation with ansible from this repository should work on all ubuntu 18.04 boxes out there.

Regards!
