### ISSUE TITLE
MySQL root access?

### ISSUE THREAD

**Issue by macidev** [shopwareLabs/shopware-platform-vagrant#18]
Hi, 

currently there's no login for root as in previous vagrant for shopware 5. 

Thanks a lot for your help. 

Kind Regards
Marcus

**Comment by flohessling** [comment]
Hi @macidev,

where do you want to login as root? 
For full access to the shopware database there is the user `app` defined in the `.psh.yaml.override` template file. 

The root user is not configured by ansible in this setup.
You should be able to ssh into the vagrant box via `vagrant ssh` and execute `sudo mysql` to get root access to the MySQL instance of this vagrant box.

I hope this helps!

**Comment by macidev** [comment]
thanks a lot.
