### ISSUE TITLE
TASK [common : install packages required for shopware.dev setup] - fatal: [default]: FAILED!

### ISSUE THREAD

**Issue by granitibrahimi** [shopwareLabs/shopware-platform-vagrant#19]
This is the issue I am getting even though I deleted the box and retried several times.

Oracle VM Version 6.1.10 r138449 (Qt5.6.2)
Vagrant: 2.2.9

Windows 10 Pro
Version: 2004
OS Build: 19041.330
64bit

`TASK [common : install packages required for shopware.dev setup] ***************
fatal: [default]: FAILED! => {"cache_update_time": 1592416250, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'apt-transport-https' 'php' 'libapache2-mod-php' 'php-cli' 'mysql-server' 'python-mysqldb' 'composer' 'nodejs' 'chromium-browser' 'default-jre-headless' 'docker.io' 'docker-compose'' failed: E: Failed to fetch https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.18.0-1nodesource1_amd64.deb  Hash Sum mismatch\n   Hashes of expected file:\n    - SHA256:4fc79649e75c131095c734ecb869ac97f160d93b2c30bed4a3cbcd3aad2faff4\n    - SHA1:e5cd717018ed31e1e6d8fc0dc1929f01eb36aa55 [weak]\n    - MD5Sum:84e2bf56d16a5b5ab8ce4ca9f41af388 [weak]\n    - Filesize:18123826 [weak]\n   Hashes of received file:\n    - SHA256:cfd23abd2650525cfb81f99f937df41c910cafe82d1139aeea49378ef3eb7663\n    - SHA1:6c89f8fbff0b72d0235023d641c5e57825f744c9 [weak]\n    - MD5Sum:94a5b95c520fc1d724d9f6d21cd2e466 [weak]\n    - Filesize:18123826 [weak]\n   Last modification reported: Tue, 02 Jun 2020 19:13:35 +0000\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.18.0-1nodesource1_amd64.deb  Hash Sum mismatch\n   Hashes of expected file:\n    - SHA256:4fc79649e75c131095c734ecb869ac97f160d93b2c30bed4a3cbcd3aad2faff4\n    - SHA1:e5cd717018ed31e1e6d8fc0dc1929f01eb36aa55 [weak]\n    - MD5Sum:84e2bf56d16a5b5ab8ce4ca9f41af388 [weak]\n    - Filesize:18123826 [weak]\n   Hashes of received file:\n    - SHA256:cfd23abd2650525cfb81f99f937df41c910cafe82d1139aeea49378ef3eb7663\n    - SHA1:6c89f8fbff0b72d0235023d641c5e57825f744c9 [weak]\n    - MD5Sum:94a5b95c520fc1d724d9f6d21cd2e466 [weak]\n    - Filesize:18123826 [weak]\n   Last modification reported: Tue, 02 Jun 2020 19:13:35 +0000\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.18.0-1nodesource1_amd64.deb  Hash Sum mismatch", "   Hashes of expected file:", "    - SHA256:4fc79649e75c131095c734ecb869ac97f160d93b2c30bed4a3cbcd3aad2faff4", "    - SHA1:e5cd717018ed31e1e6d8fc0dc1929f01eb36aa55 [weak]", "    - MD5Sum:84e2bf56d16a5b5ab8ce4ca9f41af388 [weak]", "    - Filesize:18123826 [weak]", "   Hashes of received file:", "    - SHA256:cfd23abd2650525cfb81f99f937df41c910cafe82d1139aeea49378ef3eb7663", "    - SHA1:6c89f8fbff0b72d0235023d641c5e57825f744c9 [weak]", "    - MD5Sum:94a5b95c520fc1d724d9f6d21cd2e466 [weak]", "    - Filesize:18123826 [weak]", "   Last modification reported: Tue, 02 Jun 2020 19:13:35 +0000", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  linux-image-unsigned-4.15.0-76-generic linux-modules-4.15.0-76-generic\nUse 'sudo apt autoremove' to remove them.\nThe following additional packages will be installed:\n  adwaita-icon-theme apache2 apache2-bin apache2-data apache2-utils\n  at-spi2-core bridge-utils ca-certificates-java cgroupfs-mount\n  chromium-browser-l10n chromium-codecs-ffmpeg-extra containerd\n  dconf-gsettings-backend dconf-service fontconfig fontconfig-config\n  fonts-dejavu-core glib-networking glib-networking-common\n  glib-networking-services golang-docker-credential-helpers\n  gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme\n  humanity-icon-theme java-common jsonlint libaio1 libapache2-mod-php7.2\n  libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libasound2\n  libasound2-data libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0\n  libauthen-sasl-perl libcairo-gobject2 libcairo2 libcolord2 libcroco3\n  libdata-dump-perl libdatrie1 libdconf1 libdrm-amdgpu1 libdrm-intel1\n  libdrm-nouveau2 libdrm-radeon1 libepoxy0 libevent-core-2.1-6\n  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl\n  libfile-mimeinfo-perl libfont-afm-perl libfontconfig1 libfontenc1 libgbm1\n  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgl1\n  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0 libglx-mesa0 libglx0\n  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libharfbuzz0b\n  libhtml-form-perl libhtml-format-perl libhtml-template-perl\n  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl\n  libhttp-negotiate-perl libice6 libio-socket-ssl-perl\n  libipc-system-simple-perl libjbig0 libjpeg-turbo8 libjpeg8\n  libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libllvm9 liblua5.2-0\n  liblwp-protocol-https-perl libmailtools-perl libmysqlclient20\n  libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl\n  libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0\n  libpciaccess0 libpcsclite1 libpixman-1-0 libproxy1v5 librest-0.7-0\n  librsvg2-2 librsvg2-common libsecret-1-0 libsecret-common libsensors4 libsm6\n  libsodium23 libsoup-gnome2.4-1 libsoup2.4-1 libthai-data libthai0\n  libtie-ixhash-perl libtiff5 libtry-tiny-perl libwayland-client0\n  libwayland-cursor0 libwayland-egl1 libwayland-server0 libwww-perl\n  libwww-robotrules-perl libx11-6 libx11-data libx11-protocol-perl libx11-xcb1\n  libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0\n  libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1\n  libxcursor1 libxdamage1 libxext6 libxfixes3 libxft2 libxi6 libxinerama1\n  libxkbcommon0 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl\n  libxmu6 libxmuu1 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6\n  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 mysql-client-5.7\n  mysql-client-core-5.7 mysql-common mysql-server-5.7 mysql-server-core-5.7\n  openjdk-11-jre-headless perl-openssl-defaults php-cli-prompt php-common\n  php-composer-ca-bundle php-composer-semver php-composer-spdx-licenses\n  php-json-schema php-psr-log php-symfony-console php-symfony-debug\n  php-symfony-filesystem php-symfony-finder php-symfony-polyfill-mbstring\n  php-symfony-process php7.2 php7.2-cli php7.2-common php7.2-json\n  php7.2-opcache php7.2-readline pigz python-backports.ssl-match-hostname\n  python-cached-property python-certifi python-chardet python-docker\n  python-dockerpty python-dockerpycreds python-docopt python-funcsigs\n  python-functools32 python-jsonschema python-mock python-openssl python-pbr\n  python-requests python-texttable python-urllib3 python-websocket runc\n  ssl-cert ubuntu-fan ubuntu-mono x11-common x11-utils x11-xserver-utils\n  xdg-utils\nSuggested packages:\n  apache2-doc apache2-suexec-pristine | apache2-suexec-custom\n  webaccounts-chromium-extension unity-chromium-extension adobe-flashplugin\n  fossil mercurial subversion php-zip default-jre aufs-tools debootstrap\n  docker-doc rinse zfs-fuse | zfsutils php-pear libasound2-plugins alsa-utils\n  libdigest-hmac-perl libgssapi-perl colord gvfs libipc-sharedcache-perl\n  liblcms2-utils libcrypt-ssleay-perl pcscd librsvg2-bin lm-sensors\n  libauthen-ntlm-perl libunicode-map8-perl libunicode-string-perl\n  xml-twig-tools mailx tinyca libnss-mdns fonts-dejavu-extra\n  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei\n  | fonts-wqy-zenhei fonts-indic php-symfony-event-dispatcher php-symfony-lock\n  php-mbstring python-funcsigs-doc python-mock-doc python-egenix-mxdatetime\n  python-mysqldb-dbg python-openssl-doc python-openssl-dbg python-socks\n  python-ntlm openssl-blacklist mesa-utils nickle cairo-5c xorg-docs-core\nThe following NEW packages will be installed:\n  adwaita-icon-theme apache2 apache2-bin apache2-data apache2-utils\n  apt-transport-https at-spi2-core bridge-utils ca-certificates-java\n  cgroupfs-mount chromium-browser chromium-browser-l10n\n  chromium-codecs-ffmpeg-extra composer containerd dconf-gsettings-backend\n  dconf-service default-jre-headless docker-compose docker.io fontconfig\n  fontconfig-config fonts-dejavu-core glib-networking glib-networking-common\n  glib-networking-services golang-docker-credential-helpers\n  gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme\n  humanity-icon-theme java-common jsonlint libaio1 libapache2-mod-php\n  libapache2-mod-php7.2 libapr1 libaprutil1 libaprutil1-dbd-sqlite3\n  libaprutil1-ldap libasound2 libasound2-data libatk-bridge2.0-0 libatk1.0-0\n  libatk1.0-data libatspi2.0-0 libauthen-sasl-perl libcairo-gobject2 libcairo2\n  libcolord2 libcroco3 libdata-dump-perl libdatrie1 libdconf1 libdrm-amdgpu1\n  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libepoxy0 libevent-core-2.1-6\n  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl\n  libfile-mimeinfo-perl libfont-afm-perl libfontconfig1 libfontenc1 libgbm1\n  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgl1\n  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0 libglx-mesa0 libglx0\n  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libharfbuzz0b\n  libhtml-form-perl libhtml-format-perl libhtml-template-perl\n  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl\n  libhttp-negotiate-perl libice6 libio-socket-ssl-perl\n  libipc-system-simple-perl libjbig0 libjpeg-turbo8 libjpeg8\n  libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libllvm9 liblua5.2-0\n  liblwp-protocol-https-perl libmailtools-perl libmysqlclient20\n  libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl\n  libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0\n  libpciaccess0 libpcsclite1 libpixman-1-0 libproxy1v5 librest-0.7-0\n  librsvg2-2 librsvg2-common libsecret-1-0 libsecret-common libsensors4 libsm6\n  libsodium23 libsoup-gnome2.4-1 libsoup2.4-1 libthai-data libthai0\n  libtie-ixhash-perl libtiff5 libtry-tiny-perl libwayland-client0\n  libwayland-cursor0 libwayland-egl1 libwayland-server0 libwww-perl\n  libwww-robotrules-perl libx11-6 libx11-data libx11-protocol-perl libx11-xcb1\n  libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0\n  libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1\n  libxcursor1 libxdamage1 libxext6 libxfixes3 libxft2 libxi6 libxinerama1\n  libxkbcommon0 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl\n  libxmu6 libxmuu1 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6\n  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 mysql-client-5.7\n  mysql-client-core-5.7 mysql-common mysql-server mysql-server-5.7\n  mysql-server-core-5.7 nodejs openjdk-11-jre-headless perl-openssl-defaults\n  php php-cli php-cli-prompt php-common php-composer-ca-bundle\n  php-composer-semver php-composer-spdx-licenses php-json-schema php-psr-log\n  php-symfony-console php-symfony-debug php-symfony-filesystem\n  php-symfony-finder php-symfony-polyfill-mbstring php-symfony-process php7.2\n  php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline pigz\n  python-backports.ssl-match-hostname python-cached-property python-certifi\n  python-chardet python-docker python-dockerpty python-dockerpycreds\n  python-docopt python-funcsigs python-functools32 python-jsonschema\n  python-mock python-mysqldb python-openssl python-pbr python-requests\n  python-texttable python-urllib3 python-websocket runc ssl-cert ubuntu-fan\n  ubuntu-mono x11-common x11-utils x11-xserver-utils xdg-utils\n0 upgraded, 234 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 18.1 MB/260 MB of archives.\nAfter this operation, 1410 MB of additional disk space will be used.\nGet:1 https://deb.nodesource.com/node_12.x bionic/main amd64 nodejs amd64 12.18.0-1nodesource1 [18.1 MB]\nErr:1 https://deb.nodesource.com/node_12.x bionic/main amd64 nodejs amd64 12.18.0-1nodesource1\n  Hash Sum mismatch\n  Hashes of expected file:\n   - SHA256:4fc79649e75c131095c734ecb869ac97f160d93b2c30bed4a3cbcd3aad2faff4\n   - SHA1:e5cd717018ed31e1e6d8fc0dc1929f01eb36aa55 [weak]\n   - MD5Sum:84e2bf56d16a5b5ab8ce4ca9f41af388 [weak]\n   - Filesize:18123826 [weak]\n  Hashes of received file:\n   - SHA256:cfd23abd2650525cfb81f99f937df41c910cafe82d1139aeea49378ef3eb7663\n   - SHA1:6c89f8fbff0b72d0235023d641c5e57825f744c9 [weak]\n   - MD5Sum:94a5b95c520fc1d724d9f6d21cd2e466 [weak]\n   - Filesize:18123826 [weak]\n  Last modification reported: Tue, 02 Jun 2020 19:13:35 +0000\nFetched 18.1 MB in 4s (4924 kB/s)\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  linux-image-unsigned-4.15.0-76-generic linux-modules-4.15.0-76-generic", "Use 'sudo apt autoremove' to remove them.", "The following additional packages will be installed:", "  adwaita-icon-theme apache2 apache2-bin apache2-data apache2-utils", "  at-spi2-core bridge-utils ca-certificates-java cgroupfs-mount", "  chromium-browser-l10n chromium-codecs-ffmpeg-extra containerd", "  dconf-gsettings-backend dconf-service fontconfig fontconfig-config", "  fonts-dejavu-core glib-networking glib-networking-common", "  glib-networking-services golang-docker-credential-helpers", "  gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme", "  humanity-icon-theme java-common jsonlint libaio1 libapache2-mod-php7.2", "  libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libasound2", "  libasound2-data libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0", "  libauthen-sasl-perl libcairo-gobject2 libcairo2 libcolord2 libcroco3", "  libdata-dump-perl libdatrie1 libdconf1 libdrm-amdgpu1 libdrm-intel1", "  libdrm-nouveau2 libdrm-radeon1 libepoxy0 libevent-core-2.1-6", "  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl", "  libfile-mimeinfo-perl libfont-afm-perl libfontconfig1 libfontenc1 libgbm1", "  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgl1", "  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0 libglx-mesa0 libglx0", "  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libharfbuzz0b", "  libhtml-form-perl libhtml-format-perl libhtml-template-perl", "  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl", "  libhttp-negotiate-perl libice6 libio-socket-ssl-perl", "  libipc-system-simple-perl libjbig0 libjpeg-turbo8 libjpeg8", "  libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libllvm9 liblua5.2-0", "  liblwp-protocol-https-perl libmailtools-perl libmysqlclient20", "  libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl", "  libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0", "  libpciaccess0 libpcsclite1 libpixman-1-0 libproxy1v5 librest-0.7-0", "  librsvg2-2 librsvg2-common libsecret-1-0 libsecret-common libsensors4 libsm6", "  libsodium23 libsoup-gnome2.4-1 libsoup2.4-1 libthai-data libthai0", "  libtie-ixhash-perl libtiff5 libtry-tiny-perl libwayland-client0", "  libwayland-cursor0 libwayland-egl1 libwayland-server0 libwww-perl", "  libwww-robotrules-perl libx11-6 libx11-data libx11-protocol-perl libx11-xcb1", "  libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0", "  libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1", "  libxcursor1 libxdamage1 libxext6 libxfixes3 libxft2 libxi6 libxinerama1", "  libxkbcommon0 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl", "  libxmu6 libxmuu1 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6", "  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 mysql-client-5.7", "  mysql-client-core-5.7 mysql-common mysql-server-5.7 mysql-server-core-5.7", "  openjdk-11-jre-headless perl-openssl-defaults php-cli-prompt php-common", "  php-composer-ca-bundle php-composer-semver php-composer-spdx-licenses", "  php-json-schema php-psr-log php-symfony-console php-symfony-debug", "  php-symfony-filesystem php-symfony-finder php-symfony-polyfill-mbstring", "  php-symfony-process php7.2 php7.2-cli php7.2-common php7.2-json", "  php7.2-opcache php7.2-readline pigz python-backports.ssl-match-hostname", "  python-cached-property python-certifi python-chardet python-docker", "  python-dockerpty python-dockerpycreds python-docopt python-funcsigs", "  python-functools32 python-jsonschema python-mock python-openssl python-pbr", "  python-requests python-texttable python-urllib3 python-websocket runc", "  ssl-cert ubuntu-fan ubuntu-mono x11-common x11-utils x11-xserver-utils", "  xdg-utils", "Suggested packages:", "  apache2-doc apache2-suexec-pristine | apache2-suexec-custom", "  webaccounts-chromium-extension unity-chromium-extension adobe-flashplugin", "  fossil mercurial subversion php-zip default-jre aufs-tools debootstrap", "  docker-doc rinse zfs-fuse | zfsutils php-pear libasound2-plugins alsa-utils", "  libdigest-hmac-perl libgssapi-perl colord gvfs libipc-sharedcache-perl", "  liblcms2-utils libcrypt-ssleay-perl pcscd librsvg2-bin lm-sensors", "  libauthen-ntlm-perl libunicode-map8-perl libunicode-string-perl", "  xml-twig-tools mailx tinyca libnss-mdns fonts-dejavu-extra", "  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei", "  | fonts-wqy-zenhei fonts-indic php-symfony-event-dispatcher php-symfony-lock", "  php-mbstring python-funcsigs-doc python-mock-doc python-egenix-mxdatetime", "  python-mysqldb-dbg python-openssl-doc python-openssl-dbg python-socks", "  python-ntlm openssl-blacklist mesa-utils nickle cairo-5c xorg-docs-core", "The following NEW packages will be installed:", "  adwaita-icon-theme apache2 apache2-bin apache2-data apache2-utils", "  apt-transport-https at-spi2-core bridge-utils ca-certificates-java", "  cgroupfs-mount chromium-browser chromium-browser-l10n", "  chromium-codecs-ffmpeg-extra composer containerd dconf-gsettings-backend", "  dconf-service default-jre-headless docker-compose docker.io fontconfig", "  fontconfig-config fonts-dejavu-core glib-networking glib-networking-common", "  glib-networking-services golang-docker-credential-helpers", "  gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme", "  humanity-icon-theme java-common jsonlint libaio1 libapache2-mod-php", "  libapache2-mod-php7.2 libapr1 libaprutil1 libaprutil1-dbd-sqlite3", "  libaprutil1-ldap libasound2 libasound2-data libatk-bridge2.0-0 libatk1.0-0", "  libatk1.0-data libatspi2.0-0 libauthen-sasl-perl libcairo-gobject2 libcairo2", "  libcolord2 libcroco3 libdata-dump-perl libdatrie1 libdconf1 libdrm-amdgpu1", "  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libepoxy0 libevent-core-2.1-6", "  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl", "  libfile-mimeinfo-perl libfont-afm-perl libfontconfig1 libfontenc1 libgbm1", "  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgl1", "  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0 libglx-mesa0 libglx0", "  libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libharfbuzz0b", "  libhtml-form-perl libhtml-format-perl libhtml-template-perl", "  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl", "  libhttp-negotiate-perl libice6 libio-socket-ssl-perl", "  libipc-system-simple-perl libjbig0 libjpeg-turbo8 libjpeg8", "  libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libllvm9 liblua5.2-0", "  liblwp-protocol-https-perl libmailtools-perl libmysqlclient20", "  libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl", "  libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0", "  libpciaccess0 libpcsclite1 libpixman-1-0 libproxy1v5 librest-0.7-0", "  librsvg2-2 librsvg2-common libsecret-1-0 libsecret-common libsensors4 libsm6", "  libsodium23 libsoup-gnome2.4-1 libsoup2.4-1 libthai-data libthai0", "  libtie-ixhash-perl libtiff5 libtry-tiny-perl libwayland-client0", "  libwayland-cursor0 libwayland-egl1 libwayland-server0 libwww-perl", "  libwww-robotrules-perl libx11-6 libx11-data libx11-protocol-perl libx11-xcb1", "  libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0", "  libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb1 libxcomposite1", "  libxcursor1 libxdamage1 libxext6 libxfixes3 libxft2 libxi6 libxinerama1", "  libxkbcommon0 libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl", "  libxmu6 libxmuu1 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6", "  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 mysql-client-5.7", "  mysql-client-core-5.7 mysql-common mysql-server mysql-server-5.7", "  mysql-server-core-5.7 nodejs openjdk-11-jre-headless perl-openssl-defaults", "  php php-cli php-cli-prompt php-common php-composer-ca-bundle", "  php-composer-semver php-composer-spdx-licenses php-json-schema php-psr-log", "  php-symfony-console php-symfony-debug php-symfony-filesystem", "  php-symfony-finder php-symfony-polyfill-mbstring php-symfony-process php7.2", "  php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline pigz", "  python-backports.ssl-match-hostname python-cached-property python-certifi", "  python-chardet python-docker python-dockerpty python-dockerpycreds", "  python-docopt python-funcsigs python-functools32 python-jsonschema", "  python-mock python-mysqldb python-openssl python-pbr python-requests", "  python-texttable python-urllib3 python-websocket runc ssl-cert ubuntu-fan", "  ubuntu-mono x11-common x11-utils x11-xserver-utils xdg-utils", "0 upgraded, 234 newly installed, 0 to remove and 0 not upgraded.", "Need to get 18.1 MB/260 MB of archives.", "After this operation, 1410 MB of additional disk space will be used.", "Get:1 https://deb.nodesource.com/node_12.x bionic/main amd64 nodejs amd64 12.18.0-1nodesource1 [18.1 MB]", "Err:1 https://deb.nodesource.com/node_12.x bionic/main amd64 nodejs amd64 12.18.0-1nodesource1", "  Hash Sum mismatch", "  Hashes of expected file:", "   - SHA256:4fc79649e75c131095c734ecb869ac97f160d93b2c30bed4a3cbcd3aad2faff4", "   - SHA1:e5cd717018ed31e1e6d8fc0dc1929f01eb36aa55 [weak]", "   - MD5Sum:84e2bf56d16a5b5ab8ce4ca9f41af388 [weak]", "   - Filesize:18123826 [weak]", "  Hashes of received file:", "   - SHA256:cfd23abd2650525cfb81f99f937df41c910cafe82d1139aeea49378ef3eb7663", "   - SHA1:6c89f8fbff0b72d0235023d641c5e57825f744c9 [weak]", "   - MD5Sum:94a5b95c520fc1d724d9f6d21cd2e466 [weak]", "   - Filesize:18123826 [weak]", "  Last modification reported: Tue, 02 Jun 2020 19:13:35 +0000", "Fetched 18.1 MB in 4s (4924 kB/s)"]}`

**Comment by flohessling** [comment]
Hi @granitibrahimi,

sorry but i cannot reproduce your issue with my setup.
My guess is it is related to your host when deleting the box does not work. 
Are you behind a firewall or proxy which blocks curl or apt-get? The logs you posted say, that apt-get was unable to load / check nodeJS for installation. I found issues similar to this leading me to proxy configuration.

**Comment by granitibrahimi** [comment]
Hi @f0x7C0,

thanks for the answer, this really helped. After I have disabled all firewalls (Windows 10) it passed that step. Now it has another issue which is somehow related to GIT I think:

`TASK [shopware-dev : clone shopware platform git repo] *************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://github.com/shopware/platform.git /home/vagrant/shopware-dev/platform", "msg": "Cloning into '/home/vagrant/shopware-dev/platform'...\nerror: inflate: data stream error (incorrect data check)\nfatal: pack has bad object at offset 4400152: inflate returned -3\nfatal: index-pack failed", "rc": 128, "stderr": "Cloning into '/home/vagrant/shopware-dev/platform'...\nerror: inflate: data stream error (incorrect data check)\nfatal: pack has bad object at offset 4400152: inflate returned -3\nfatal: index-pack failed\n", "stderr_lines": ["Cloning into '/home/vagrant/shopware-dev/platform'...", "error: inflate: data stream error (incorrect data check)", "fatal: pack has bad object at offset 4400152: inflate returned -3", "fatal: index-pack failed"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
default                    : ok=16   changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by flohessling** [comment]
Hi @granitibrahimi,

again i am not able to reproduce this issue. 
I think this could be related to many things happening. For example it could be a malware-scanner / anti-virus software on your client that scans the data while it is being downloaded by `git clone`. Another possibility is a very slow network connection or low memory on your client.

Sorry that i cannot provide a direct solution for this issue. I hope this helps anyway! 

Cheers, F.
