### ISSUE TITLE
Wrong package provided for apt-get

### ISSUE THREAD

**Issue by ruffiely** [shopwareLabs/shopware-platform-vagrant#2]
On vagrant up:
default: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y -qq software-properties-common python-software-properties

Stdout from the command:

Stderr from the command:

E: Package 'python-software-properties' has no installation candidate

**Comment by ruffiely** [comment]
Seems like a problem with my vagrant version.
Workaround is either to update vagrant or just add ansible.install_mode = "pip" to Vagrantfile

**Comment by mika350** [comment]
Updating vagrant (from 2.0 to 2.2) worked for me.
