### ISSUE TITLE
Ansible task returned error

### ISSUE THREAD

**Issue by rammi22** [shopwareLabs/shopware-platform-vagrant#21]
Hello,
i try to install Shopware 6.2.**3** with the Vagrant Box

File all.yml

`
---
proxy_enabled: yes
proxy_hostname: dev.shopware-6.2.3.local
proxy_ssl: yes
shopware_version: 6.2.3
`
vagrant up with this configuration return this error:

> TASK [clone shopware-dev git repo] *********************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 6.2.3", "msg": "Failed to checkout 6.2.3", "rc": 1, "stderr": "error: pathsp
ec '6.2.3' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec '6.2.3' did not match any file(s) known to git."], "stdout": "", "stdout_
lines": []}

I expect a correct installation.

**Comment by flohessling** [comment]
Hey @rammi22 ,

sorry for the late response. 
The string `6.2.3` is no tag or branch of the shopware development repository https://github.com/shopware/development. 

When using the `v6.2.3` tag for `shopware_version` it should work.

```
---
proxy_enabled: no
proxy_hostname: shopware.local
proxy_ssl: no
shopware_version: v6.2.3
```
