### ISSUE TITLE
vagrant up fails with "Failed to checkout master"

### ISSUE THREAD

**Issue by RaiMed** [shopwareLabs/shopware-platform-vagrant#29]
vagrant up fails with the following error message for me:

TASK [clone shopware-dev git repo] *********************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force master", "msg": "Failed to checkout master", "rc": 1, "stderr": "error: pathspec 'master' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec 'master' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
default                    : ok=15   changed=11   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by ghost** [comment]
I receive the exact same error.

**Comment by xx3w** [comment]
Same.

The reason is probably this:
https://www.shopware.com/en/news/shopware-will-switch-to-scaled-trunk-based-development/

**Comment by xx3w** [comment]
helped for me: 

changing the shopware_version from master to tag in all.yml

```
proxy_enabled: no
proxy_hostname: shopware.local
proxy_ssl: no
shopware_version: v6.3.5.1
```

**Comment by shyim** [comment]
Changed already in master here to trunk
