### ISSUE TITLE
[Feature] Add option to enable TLS and HTTP/2

### ISSUE THREAD

**Issue by rherwig** [shopwareLabs/shopware-platform-vagrant#5]
In order to provide a development environment that is a little closer to real-world environments, I would appreciate the possibility to enable TLS and HTTP/2 (maybe in conjunction with nginx as reverse proxy).

Since this is just a request, please let me know, if a pull-request is appreciated or if this feature is not something you want to have integrated into the VM. :-)

**Comment by flohessling** [comment]
A pull-request is much appreciated! Feel free to add functionality that helps your development workflow. This will surely help others too! Thank you in advance!
